// RadarGas Blog — Local JSON Data Source
// Reads blog posts from src/data/blog-posts.json (auto-generated by scripts/auto-news.mjs)

import blogPostsData from '@/data/blog-posts.json';

export interface BlogPost {
    Id: number;
    Title: string;
    Slug: string;
    Excerpt: string;
    Content: string;
    CoverImage: string;
    Category: string;
    Published: boolean;
    PublishedAt: string;
}

interface RawBlogPost {
    slug: string;
    title: string;
    excerpt: string;
    content: string;
    category: string;
    coverImage: string;
    sourceUrl: string;
    sourceName: string;
    publishedAt: string;
    generatedAt: string;
}

function mapPost(raw: RawBlogPost, index: number): BlogPost {
    return {
        Id: index + 1,
        Title: raw.title,
        Slug: raw.slug,
        Excerpt: raw.excerpt,
        Content: raw.content,
        CoverImage: raw.coverImage || '',
        Category: raw.category || 'Precios',
        Published: true,
        PublishedAt: raw.publishedAt,
    };
}

/**
 * Get all published blog posts, ordered by PublishedAt descending.
 */
export async function getAllPosts(): Promise<BlogPost[]> {
    const posts = (blogPostsData as unknown as RawBlogPost[]) || [];
    return posts.map((p, i) => mapPost(p, i));
}

/**
 * Get a single post by slug.
 */
export async function getPostBySlug(slug: string): Promise<BlogPost | null> {
    const posts = (blogPostsData as unknown as RawBlogPost[]) || [];
    const found = posts.find(p => p.slug === slug);
    return found ? mapPost(found, 0) : null;
}

/**
 * Get all slugs for static generation.
 */
export async function getAllSlugs(): Promise<string[]> {
    const posts = (blogPostsData as unknown as RawBlogPost[]) || [];
    return posts.map(p => p.slug);
}
